### ISSUE TITLE
Navbar documentation

### ISSUE THREAD

**Issue by mrdionjr** [3YOURMIND/kotti#105]
**Is your feature request related to a problem? Please describe.**
I would like to customize the "header" of the navbar to include the logo of the company like in this [screenshot](https://kotti.netlify.com/_nuxt/img/bcd1386.png) shown in the layout section of the docs.

**Describe the solution you'd like**
I just want guidance on how to implement it since the navbar component does not have a header slot.

**Comment by amrdraz** [comment]
You can customise the logo using the KtTheme.logoUrl 
see Theme Configuration https://3yourmind.github.io/kotti/patterns/navbar

**Comment by mrdionjr** [comment]
Thank you, I'll just write custom CSS to achieve the same result.
