### ISSUE TITLE
Add KtFieldDateRange

### ISSUE THREAD

**Issue by amrdraz** [3YOURMIND/kotti#108]
Kotti does not have a date rang picker
we currently use element-ui's data range picker in 3yourmind

Create a date range picker inspired by element ui and update existing date range picker

It needs to support getting cleared

Attached are use cases from 3yourmind's service panel

<img width="692" alt="Screenshot 2019-10-02 at 16 46 18" src="https://user-images.githubusercontent.com/1708559/66054563-7aa1e080-e534-11e9-99aa-7e330188c02a.png">
<img width="681" alt="Screenshot 2019-10-02 at 16 46 29" src="https://user-images.githubusercontent.com/1708559/66054564-7b3a7700-e534-11e9-9f85-953600854e2c.png">

**Comment by FlorianWendelborn** [comment]
Merged into #215.
