### ISSUE TITLE
position: fixed causing navbar-wrapper elements to not appear in IE 11

### ISSUE THREAD

**Issue by justinline** [3YOURMIND/kotti#13]
https://github.com/3YOURMIND/kotti/blob/0cb1210ae947d36c4d247fd9f0fb4b1b01a646c2/packages/kotti-style/src/_navbar.scss#L13

Can be fixed by removing `position: fixed` - which doesn't seem to be necessary.

![screenshot from 2018-03-22 12-56-53](https://user-images.githubusercontent.com/6620797/37769400-298fd768-2dd1-11e8-8e90-5b27bb44c68d.png)
![screenshot from 2018-03-22 12-56-59](https://user-images.githubusercontent.com/6620797/37769406-2d78803c-2dd1-11e8-9d23-a8087f9cbee6.png)

**Comment by ostoc** [comment]
@justinline we need `position:fixed` to fix the navbar-wrapper elements. Because we need make sure it fixed on the page when workspace is too long and scrolling. I will text on IE11 again to make another fix alternative.

**Comment by justinline** [comment]
Ah yeah, that would make sense, I can workaround locally for now :+1:

**Comment by justinline** [comment]
adding `position: relative;` to it's parent element `.navbar` seems to work :smile:

**Comment by dodekeract** [comment]
@ostoc, I figured out how to make modals work in the `actionbar` without destroying the scroll behavior. My changes also seem to fix this issue:

```
// @HACK make modals work in actionbar by removing stacking contexts
.navbar {
	z-index: auto !important;
}

.actionbar-wrapper {
	height: 100vh !important;
	position: static !important;
}
```

Also, you may want to check out [this article about z-index stacking contexts](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/).

**Comment by ostoc** [comment]
@dodekeract for a working modal in `actionbar`, you just need to write the `modal` outside the scope of `actionbar`

``` 
Wrong Structure 
<actionbar>
<modal/>
</actionbar>

Correct Structure

<actionbar>
...
...
</actionbar>
...
<modal/>
```

**Comment by ostoc** [comment]
@justinline i will update the change to `kotti-style` and publish a new release.
