### ISSUE TITLE
Optimise build process 

### ISSUE THREAD

**Issue by ostoc** [3YOURMIND/kotti#15]
The webpackage build src files are not so clear, need a optimise for better auto build.

**Comment by igeligel** [comment]
I will work on a better approach with some [rollup](https://rollupjs.org/guide/en) soon.

I think we should start like atlaskit and publish each component as npm package. This requires us to import the styles locally into the components though. I will make an example the next days for the avatar component on how this is done. We can release all packages with [bolt](https://github.com/boltpkg/bolt).

**Comment by dodekeract** [comment]
@igeligel @ostoc can this be closed?
