### ISSUE TITLE
missing mixins import in kotti's bundled stylesheet

### ISSUE THREAD

**Issue by carsoli** [3YOURMIND/kotti#164]
**Describe the bug**
mixins should be included in the build 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FlorianWendelborn** [comment]
@carsoli can this be closed?

**Comment by FlorianWendelborn** [comment]
🧠
