### ISSUE TITLE
Adjust postPublish Hook to Re-Tag or Ignore

### ISSUE THREAD

**Issue by FlorianWendelborn** [3YOURMIND/kotti#165]
Right now, if ~~someone~~ @carsoli uses `npm version`, `npm` creates a local `v1.2.3` tag. Then the `postPublish` hook tries to create another one and fails, making it appear as if the publish was unsuccessful.

This can be fixed by ignoring the error or by deleting the tag first.

**Comment by carsoli** [comment]
> Right now, if ~someone~ @carsoli uses `npm version`, `npm` creates a local `v1.2.3` tag. Then the `postPublish` hook tries to create another one and fails, making it appear as if the publish was unsuccessful.
> ~@carsoli~ someone* @FlorianWendelborn

**Comment by FlorianWendelborn** [comment]
Closing as this was just merged and confirmed to be fixed by @carsoli
