### ISSUE TITLE
Move styles close to components

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/kotti#18]
We should have the stylings more near the components.

See this code for example:

```vue
<style lang="scss" scoped>
@import '../kotti-style/src/_variables.scss';
@import '../kotti-style/src/_avatar.scss';
</style>
```

This will break when you want to build the documentation because of some weird path errors.

As an example, you can also lookup how Atlassian has solved this problem here: https://bitbucket.org/atlassian/atlaskit-mk-2/src/d3a13c78b29e/packages/core/button/?at=master

Basically they have a `/src` folder per package and in this package they have again a directory called `styles` in which the styles are considering  the components they have built.

Also an anti-pattern we have right now is that every package is referenced relative. With bolt we can use pseudo imports if you want to call it like this.

**Comment by ostoc** [comment]
```
@import '../kotti-style/src/_variables.scss';
```

if you include `_variables.scss` into the component, then there is no chance to update the variables anymore. 


> This will break when you want to build the documentation because of some weird path errors.

Import style is not the reason break the build for doc. 

Error messages are: 

```bash
These relative modules were not found:

* ../../../packages/kotti-avatar-group/dist/kotti-avatar-group.esm in ./www/pages/components/avatars.vue?vue&type=script&lang=js
* ../../../packages/kotti-avatar/dist/kotti-avatar.esm in ./www/pages/components/avatars.vue?vue&type=script&lang=js

```

Because there are not such file built in `dist` dir.

**Comment by igeligel** [comment]
Because you need to build the component before.

If you try to use `../../../packages/kotti-avatar-group` then you will get the error i was talking about.
