### ISSUE TITLE
Table Doesn't Support <tbody>

### ISSUE THREAD

**Issue by dodekeract** [3YOURMIND/kotti#19]
[These lines](https://github.com/3YOURMIND/kotti/blob/824e4fadbcc1e0fa0f5aae496a50165f4e433e7f/packages/kotti-style/src/_tables.scss#L67-L75) prevent the hover effect from showing up when using `<tbody>` in a table.

I suggest changing the selector to:

```scss
> tbody > tr, > tr {}
```

**Comment by ostoc** [comment]
@dodekeract do you think you fixed this one?

**Comment by dodekeract** [comment]
@ostoc I haven’t touched that part of the CSS. I’ll try to fix it later today if this issue still exists.

**Comment by dodekeract** [comment]
This can be closed, the issue appears to be fixed already.
