### ISSUE TITLE
Typing specific numbers into InputNumber does not work correctly

### ISSUE THREAD

**Issue by Tradias** [3YOURMIND/kotti#31]
Typing 'e' or '-' after a number clear the input and set the value to NaN. If you then type 'e' or '-' you can write invalid numbers like 'ee45-e45-223'. The expected behaviour that when typing 'e' afterwards would still get cleared.

Typing a number like '10e1' does not work, because the input field gets cleared and the value turns to NaN when pressing the 'e'. Copying the number into the field however works correctly.

Numbers like '-----123' can be typed into the field. I would expect the field to get cleared when the second '-' was typed.

**Comment by ostoc** [comment]
> Typing 'e' or '-' after a number clear the input and set the value to NaN. If you then type 'e' or '-' you can write invalid numbers like 'ee45-e45-223'. The expected behaviour that when typing 'e' afterwards would still get cleared.
>Numbers like '-----123' can be typed into the field. I would expect the field to get cleared when the second '-' was typed.

The input number implemented based on:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

When we create the component we are trying to get closer to the browser implementation.

If it's NaN, the input-number field will have red border.

> Typing a number like '10e1' does not work, because the input field gets cleared and the value turns to NaN when pressing the 'e'. Copying the number into the field however works correctly.

Yes, we need fix this.

**Comment by ostoc** [comment]
Fixed in 0.0.5
