### ISSUE TITLE
KtFieldMultiSelect `width: 0px` when binding an isLoading property

### ISSUE THREAD

**Issue by carsoli** [3YOURMIND/kotti#336]
**Describe the bug**
Having a multi-select that has `isLoading` property set to true then to false, maintains a width of `0 px` on the popper

**To Reproduce**
1. Bind a loading changing prop to `isLoading` of `KtFieldMultiSelect`
2. when it's finally set to false, try to open the dropdown
3. dropdown opens but looks entirely broken, on element inspection, width is `0 px`

**Expected behavior**
Proper width is set

**Screenshots**
![Screenshot from 2021-01-04 13-54-39](https://user-images.githubusercontent.com/17387510/103532954-e3dd7580-4e94-11eb-9ef4-08acb80346c5.png)
![Screenshot from 2021-01-04 13-55-00](https://user-images.githubusercontent.com/17387510/103532955-e50ea280-4e94-11eb-958d-aa54983ba723.png)
![Screenshot from 2021-01-04 13-55-07](https://user-images.githubusercontent.com/17387510/103532957-e5a73900-4e94-11eb-95f0-8b298de7563b.png)

**Additional context**
Probably reproducible with `KtFieldSingleSelect` too, investigation and fix would probably be specific to hooks of KtField*Select

**Comment by FlorianWendelborn** [comment]
@carsoli I’d say that `ElSelect` shouldn’t even be loaded if the element is `isLoading`. Perhaps this is simply a case of having to move the hook into a separate subcomponent that wraps the `ElSelect`?

**Comment by FlorianWendelborn** [comment]
Not reproducible in <https://gitlab.3yourmind.com/dev/yoda/-/merge_requests/782#note_21435>. Perhaps gives some insight into what’s different here.

**Comment by carsoli** [comment]
can confirm it's not a `KtFieldSingleSelect` issue, but only `KtFieldMultiSelect` issue

can also confirm `isLoading` is not the deal breaker here, but having an empty list of options + another set of conditions that i'm currently investigating always replicates this issue

**Comment by carsoli** [comment]
if we check emitted events when this is reproducible, we find `updatePopper` event
and in the payload, we can check the data of the created `PopperJS` `HTMLElement` and it has `minWidth: ''`

which comes from https://github.com/ElemeFE/element/blob/649670c55a45c7343eb7148565e2d873bc3d52dd/packages/select/src/select-dropdown.vue#L61

in contrast, the same exact conditions are used for `KtFieldSingleSelect`, including a null value initially 
and it emits a `PopperJS` instance with `minWidth` equal to the parent $el width
