### ISSUE TITLE
Label-Value component in Kotti

### ISSUE THREAD

**Issue by Isokaeder** [3YOURMIND/kotti#429]
In yoda we use four different ways to create label-value patterns:

- `.label-value` pattern from Kotti ([documented here](https://3yourmind.github.io/kotti/foundations/text/typography))
- `<LabelValue>` used in MES
- `<DisplayProperty>` used in ERP
- `<PartDetailValueLabel>` used in AMPI

They don't differ in style very much and largely overlap in features. Instead of this redundancy, we should create a `KtLabelValue` component that encapsulates the css already defined for `.label-value` with a API that merges the API's of the above components, to make migration simple

### `.label-value`
Provides special css classes for its descendants:

class | description 
------|-------------
default | normal text
key | emphasized text (`font-size: 1.2rem; font-weight: 600`)
addition | somewhat emphasized text (`font-size: 0.8rem; font-weight: 600`) 
action | for icons links or other interactive elements (looks broken btw, but is not used anyway)
editable | for use within `KtInlineEdit`

#### Props
name | required | type | description 
------|---------|-----|-------------
label | ✅ | string | label / title
value | ❌ | string/number/null | value, defaults to `null`
horizontal | ❌ | boolean | arrange label and value horizontally, defaults to false 

#### Slots
name | description 
------|---------
default | rendered instead of `value`

#### Props
name | required | type | description 
------|---------|-----|-------------
label | ✅ | string | label / title
content | ❌ | string/null | value, defaults to `null`
isEmphasized | ❌ | boolean | gets emphasized visually (label: `font-size: 0.8rem; font-weight: bold; color: var(--text-01)`, value: `font-size: 1.2rem; font-weight: bold`), defaults to false 
isHorizontal | ❌ | boolean | arrange label and title horizontally, defaults to false 

#### Slots
name | description 
------|---------
default | rendered instead of `value`

#### Props
name | required | type | description 
------|---------|-----|-------------
label | ✅ | string | label / title
value | ✅ | string | value, supports markdown
isUnset | ❌ | boolean | if true show default text instead of value, defaults to false 

#### Slots
name | description 
------|---------
default | rendered instead of `value`

#### Props
name | required | type | description 
------|---------|-----|-------------
label | ✅ | string | label / title
value | ❌ | string/number/null | value, defaults to `null`
emphasis | ❌ | enum ('none', 'medium', 'big') | Styles taken from Figma for now
emphasisStyle | ❌ | enum ('full'/'value') | 'full' - label and value emphasized as in `DislayProperty`, 'value' - value emphasized as in `.value-label`, defalts to 'value'
isHorizontal | ❌ | boolean | arrange label and title horizontally, defaults to false 

#### Slots
name | description 
------|---------
default | rendered instead of `value`

regarding the css classes `addition`, `action`, and `editable` are not necessary to port IMO

**Comment by carsoli** [comment]
#817 was the first issue to deal with this
more handling will follow for price and date values (based on type prop)
