### ISSUE TITLE
Extend KtLine features

### ISSUE THREAD

**Issue by HansAuger** [3YOURMIND/kotti#439]
We have designs that put the text to the right and support links as text. That should be implemented in Kotti.

Designs: https://www.figma.com/file/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=95%3A771

**Comment by carsoli** [comment]
![Screenshot from 2021-12-10 10-47-15](https://user-images.githubusercontent.com/17387510/145553562-543b0a9a-4d4c-4f44-9f22-c142236541db.png)

Figma design not accessible outside our engineering group @HansAuger 
> posted a screenshot instead

**Comment by FlorianWendelborn** [comment]
@carsoli link works fine for me without being logged-in
