### ISSUE TITLE
Avatar component doesn't handle non square images

### ISSUE THREAD

**Issue by tomquinonero** [3YOURMIND/kotti#45]
**Describe the bug**
The Avatar components doesn't work with non square images.

**To Reproduce**
Use the component with any non square image.

**Expected behavior**
The image should be cropped, probably centered also.

**Screenshots**
![app 3ydev com_accounts_profile 2](https://user-images.githubusercontent.com/15861247/51474498-d306c880-1d7f-11e9-8978-950a56ef5bf7.png)
![app 3ydev com_accounts_profile 3](https://user-images.githubusercontent.com/15861247/51474736-7e178200-1d80-11e9-985f-ee3d18c54ba2.png)

**Comment by FlorianWendelborn** [comment]
@ostoc does the fix also center the image? I thought you need to explicitly tell CSS to do that, but I’m not sure

**Comment by ostoc** [comment]
@FlorianWendelborn i think so.
