### ISSUE TITLE
KtModal: Support Escaping CSS Stacking Context

### ISSUE THREAD

**Issue by FlorianWendelborn** [3YOURMIND/kotti#478]
Currently, using a modal from within a CSS stacking context means that the modal itself will be rendered from within the CSS stacking context. This obviously yields overlapping elements from the page and is hard to fix from outside of kotti.

Possible solutions include:

* Fully upgrading to vue 3 and using `<Teleport>`
* [using tippy.js in headless mode](https://atomiks.github.io/tippyjs/v6/headless-tippy/)
* using `portal-vue`

**Comment by carsoli** [comment]
closed by #637
