### ISSUE TITLE
KtNumberInput not working in IE

### ISSUE THREAD

**Issue by justinline** [3YOURMIND/kotti#52]
**Describe the bug**
Using the KtNumberInput does not allow clicking the + and - buttons in IE

**To Reproduce**
1. Go to https://3yourmind.github.io/kotti/components/inputnumber/ (In IE11)
2. Try clicking the steppers
3. No value change happens.
4. Can still type the number as expected and click the X 

**Expected behavior**
Value should change

**Screenshots**
![stepper](https://user-images.githubusercontent.com/6620797/51977440-c3763680-2487-11e9-9cc4-f2f0a97da39e.gif)

**Desktop (please complete the following information):**
 - OS: Virtualbox
 - Browser IE 11

**Comment by Goldziher** [comment]
This issue is still present

**Comment by Goldziher** [comment]
resolved in 1.6
