### ISSUE TITLE
Kt Popover options should support non-interactive items

### ISSUE THREAD

**Issue by Isokaeder** [3YOURMIND/kotti#536]
**Describe the bug**
We force options to always be interactive, as we either want them to be disabled or have a click event handler. However, sometimes we use KtPopover just to show some labels that display information without interactivity.

**Expected behavior**
If one option neither is disabled nor provides a click event handler, render as item -> background and cursor don't changeg on hover

**Comment by carsoli** [comment]
closed by #395
