### ISSUE TITLE
allow knowing when KtPopover has mounted in order to be able select DOM elements in the body

### ISSUE THREAD

**Issue by amrdraz** [3YOURMIND/kotti#62]
**Is your feature request related to a problem? Please describe.**
sometimes this happens
<img width="321" alt="screenshot 2019-02-27 12 53 43" src="https://user-images.githubusercontent.com/1708559/53488591-10e9c180-3a8f-11e9-954c-c447598d2948.png">
when this should happen
<img width="317" alt="screenshot 2019-02-27 12 53 49" src="https://user-images.githubusercontent.com/1708559/53488593-10e9c180-3a8f-11e9-84a2-8f9f614aceb1.png">

**Describe the solution you'd like**
I want the mounted hook to $emit('mounted') or $emit('opened') when the popoover has opened for ceratin
 cause apparently Vue.nextTick isn't working even though it should

**Describe alternatives you've considered**
so far I wait a couple of event loops and select the elements by attribute and if the element isn't there yet

**Additional context**
this is for the KtTimePicker

**Comment by amrdraz** [comment]
@ostoc  I could handle this when adding KtTimeInput I'm just adding it to remember

**Comment by FlorianWendelborn** [comment]
Closing due to the new Kotti Fields landing soon, making this redundant.
