### ISSUE TITLE
KtNavBar Border color change

### ISSUE THREAD

**Issue by justinline** [3YOURMIND/kotti#63]
**Is your feature request related to a problem? Please describe.**
The borders for KtNavBar have opacity but doesn't work well with KtNavTheme overrides

**Describe the solution you'd like**
Would be great to have the Borders calculated based on whether the background color is light or dark :)

**Comment by ostoc** [comment]
@justinline The API changes will change when next release, you don't need to specify the borderColor anymore. 

**Prvider name changed from `KtNavbarTheme` to `KtTheme`**

Default Theme Provider

```js
provide() {
	return {
		KtTheme: {
			navbarBackgroundColor: '#122C56',
			navbarTextColor: 'rgba(255,255,255,.54)',
			navbarTextActiveColor: 'rgba(255,255,255, 1)',
			logoUrl: LogoSvg,
			logoHeight: '40px',
		},
	}
},
```
This change should be also important to @FlorianWendelborn @tomquinonero
