### ISSUE TITLE
KtNavbar: use object for link like in router-link components

### ISSUE THREAD

**Issue by tomquinonero** [3YOURMIND/kotti#65]
In `vue-router` (and in life in general) when creating a link it is recommended to rely on a link name rather than a path.
The `<router-link>` component can accept both: <https://router.vuejs.org/api/#to>

I think the `NavBar` links should have the same API. Accepting a string as a path or an object. Under the hood, we just have to "pass" the props to a `router-link` component and the job's done 👍

**Comment by FlorianWendelborn** [comment]
While I think there needs to be a solution for this use-case, I don’t think Kotti should rely on third-party global dependencies. We should rather handle this via dependency injection. What do you think @tomquinonero @carsoli?

**Comment by FlorianWendelborn** [comment]
@carsoli and I decided that dependency injection is probably a good idea.

**Comment by HansAuger** [comment]
Closed by #549
