### ISSUE TITLE
Documentation: Navbar Active State is Broken

### ISSUE THREAD

**Issue by FlorianWendelborn** [3YOURMIND/kotti#662]
1. https://3yourmind.github.io/kotti/usage/components/accordion/
2. Click "Layouts"
3. Notice how Components is still "active" although it should be "Layouts". Fixed on reload.

Assuming this is not broken for all KtNavbars, this is pretty low priority. If it turns out to be broken everywhere, please mark as priority 4.

**Comment by FlorianWendelborn** [comment]
This also appears to only be broken for certain menu entries (some work). No idea why.

**Comment by HansAuger** [comment]
I fixed this by wrapping [`sections` in NavBar.vue](https://github.com/3YOURMIND/kotti/blob/master/packages/documentation/components/NavBar.vue#L82-L104) in a computed.

However, it's also strange that we set [`color: inherit` here](https://github.com/3YOURMIND/kotti/blob/master/packages/kotti-ui/source/kotti-navbar/components/NavbarMenu.vue#L82). On Firefox that makes the wrongly inactive menu item have the default color for `<a>`
