### ISSUE TITLE
KtTable have glitchy checkboxes when KtTable has isSelectable to true

### ISSUE THREAD

**Issue by RueRivoli** [3YOURMIND/kotti#674]
**Describe the bug**
The checkboxes of selectable tables are glitchy

**To Reproduce**
Go to any KtTable that has the property `isSelectable` prop set to true
You see the screenshot below

**Expected behavior**
Checkboxes are not glitchy

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/17473800/201733289-f1eae5cd-2302-43fb-8547-48709c0522b9.png)

**Comment by carsoli** [comment]
Closed by #684
