### ISSUE TITLE
Inline edit improvement

### ISSUE THREAD

**Issue by tomquinonero** [3YOURMIND/kotti#68]
The inline-edit should be more user-friendly. I don't think label makes sense there, neither invalidMessage.

I'd like a simple solution, looking like JIRA for example. I don't think multiline matters actually.

**Comment by ostoc** [comment]
@tomquinonero 

- label is need in some case, at lease in design
- invalidMessage also need, this was added due to another requirement 
- multiline also matters, it's been used by @amrdraz

**Comment by amrdraz** [comment]
opps sorry closed by mistake
but is not clear what should be improved

I would appreciate an @change event independent of the v-model @input so that I can use both

**Comment by tomquinonero** [comment]
We decided that for now, this improvement is out of scope for kotti. It has been implemented internally and may be outsourced in the future.
