### ISSUE TITLE
Fix arrow style in KtBreadcrumbs

### ISSUE THREAD

**Issue by RueRivoli** [3YOURMIND/kotti#682]
**Describe the bug**
Hovering over an arrow changes text's color.

**To Reproduce**

1. Go to the documentation of `KtBreadcrumbs`
2. Hover any arrow before a step (except for disabled steps).
3. It changes the step's text color.

**Expected behavior**
Hovering over the arrow should not change the text's color of the step.

**Comment by carsoli** [comment]
Closed by #683
