### ISSUE TITLE
Add label indicators next to default slot

### ISSUE THREAD

**Issue by santiagoballadares** [3YOURMIND/kotti#699]
**Is your feature request related to a problem? Please describe.**
In `KtFieldToggle`, show required `*` and optional `(Optional)` indicators next to `Default slot` when `Default slot` is used instead of `label`

**Describe the solution you'd like**
Show required `*` and optional `(Optional)` indicators next to `Default slot`

**Describe alternatives you've considered**
n/a

**Additional context**
Required for usage of `KtFieldToggle` when label should be shown on the right side rather than on top

**Comment by carsoli** [comment]
closed by #701
