### ISSUE TITLE
(Example) - Modifying kotti within yoda without publishing

### ISSUE THREAD

**Issue by RueRivoli** [3YOURMIND/kotti#716]
**Is your feature request related to a problem? Please describe.**
This MR is an example on how to modify `Kotti` on `Yoda` for debugging. The `KtDrawer` background's color is changed to blue as an example.

**Describe the solution you'd like**
Having a JIRA Ticket linked to that MR and another Yoda's MR. A flux env has to be working.

**Describe alternatives you've considered**
/

**Additional context**
This was discussed within the FE team so that everyone is familiar with modifying `Kotti` within `Yoda`.

**Comment by carsoli** [comment]
this didn't need an issue or a PR, just a local branch
